---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: multi-juicer
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/juice-shop/multi-juicer/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multi-juicer
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: multi-juicer
      # Newest `version` here:
      # https://github.com/juice-shop/multi-juicer/blob/main/helm/multi-juicer/Chart.yaml
      version: "7.2.1"
      sourceRef:
        kind: HelmRepository
        name: multi-juicer
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/juice-shop/multi-juicer/blob/main/helm/multi-juicer/values.yaml
  values:
    juiceShop:
      tag: v15.1.0
      maxInstances: 20
      resources:
        requests:
          cpu: 100m
          memory: 400Mi
        limits:
          cpu: 1000m
          memory: 400Mi
      config: |
        application:
          logo: https://raw.githubusercontent.com/juice-shop/multi-juicer/main/images/multijuicer-icon-only-padding.png
          favicon: https://raw.githubusercontent.com/juice-shop/multi-juicer/main/juice-balancer/ui/public/favicon.ico
          showVersionNumber: false
          showGitHubLinks: false
        challenges:
          showHints: true
        hackingInstructor:
          isEnabled: true
        ctf:
          showFlagsInNotifications: false

    balancer:
      metrics:
        enabled: true
        # Create dashboards in ConfigMaps for Grafana to pick up and import
        dashboards:
          enabled: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: ctf.silly.hair
          paths:
            - "/"
      tls:
        - hosts:
            - ctf.silly.hair
          secretName: tls-secret

    juiceShopCleanup:
      # After this period of being unused, the Juice Shop instance will be a candidate for deletion
      gracePeriod: 7d
      # Run the cleanup job every hour
      cron: "0 * * * *"
