---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.0" # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  # Default values:
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller:
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-dns-label-name: ctf-silly-hair
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
